services:
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - media-shared-network
  nginx:
    image: nginx:latest
    extra_hosts:
    - "host.docker.internal:host-gateway"
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - media-shared-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - media-shared-network

# docker compose -f compose/docker-compose.yml --env-file .env run --rm certbot certonly --webroot   --webroot-path=/var/www/certbot   -d savebit.ru -d www.savebit.ru --email khasanknyazev81@gmail.com   --agree-tos --no-eff-email

volumes:
  pgdata:
    driver: local

networks:
  media-shared-network:
    driver: bridge