services:
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - media-shared-network

  nginx:
    image: nginx:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ./frontend_cert/conf:/etc/letsencrypt/frontend
      - ./backend_cert/conf:/etc/letsencrypt/backend
    networks:
      - media-shared-network

networks:
  media-shared-network:
    driver: bridge
